routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes();

Route::get('/', function () {
    return redirect()->route('motor.index');
});

Route::get('/service-history', function () {

    $pakyets = \App\Service::all()->groupBy('name');
    return view('paksyet', compact('pakyets'));

})->name('yo');

Route::get('/audit-trail', function () {

    $trails = \App\Trail::all();
    return view('auditXXXXXX', compact('trails'));

})->name('at');

Route::post('penalty-penalty', 'TransactionController@penalty')->name('penalty');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/print-service', 'HomeController@xx')->name('print.service');

Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');
Route::resource('stock', 'StockController');
Route::resource('service', 'ServiceController');
Route::resource('order', 'OrderController');

Route::resource('user', 'BrandController');

Route::post('flush-orders', 'UserController@flushorders')->name('flush.orders');

Route::post('add/order/stock', 'UserController@addOrder');
Route::post('remove/order/stock', 'UserController@removeOrder');
Route::get('/motorcycles', 'StockController@getMotor')->name('motor.index');
Route::get('/parts', 'StockController@getParts');
Route::get('/cart', 'HomeController@cart')->name('cart');

Route::get('/billing', 'TransactionController@billingIndex');
Route::get('/billing/edit/{id}', 'TransactionController@billingEdit');
Route::post('/billing/edit/{id}', 'TransactionController@billingUpdate');
Route::get('/transactions', 'OrderController@transactions');
Route::get('/transaction-report', 'OrderController@transactionReport')->name('transaction.report');

Route::post('/billing/discount', 'TransactionController@billingDiscount');
Route::get('/get/search', 'StockController@getClick');
Route::post('/add/comment', 'StockController@addComment');
Route::post('/add/delete', 'StockController@deleteComment');

Route::get('/statement-of-account/{id}', 'TransactionController@fucked')->name('tadow');
Route::get('/mission-vision', 'UserController@mv');
Route::get('/viewservices', 'ServiceController@view')->name('serviceslist');

resources/views/auditXXXXXX.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
    <h2>Audit Trail</h2>
<br>
<br>
        <div class="panel panel-default">
<div class="table-responsive">
    <table class="table table-bordered" id="stock-table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Log Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($trails as $trail)
            <tr>
                <td>{{ $trail->title }}</td>
                <td>{{date('d M Y g:i:s A', strtotime($trail->created_at))}}</td>



            </tr>
            @endforeach
        </tbody>
    </table>
</div>
</div>
  <br>
    <br>
    <br>  <br>
    <br>
    <br>
@endsection

resources/views/dashboard.blade.php
@extends('layouts.app')
@section('content')
@include('partials._message')
<div class="row">
    <a href="{{ route('stock.index')}}">
        <div class="col-md-4">
            <div class="well">
                <i class="fa fa-shopping-cart fa-4x fa-fw" aria-hidden="true"></i>
                <div class="text">
                    <h3>Stocks</h3>
                    <p>Items : {{ $stock_count }}</p>
                </div>
            </div>
        </div>
    </a>
    <a href="{{url('billing')}}">
        <div class="col-md-4">
            <div class="well">
                <i class="fa fa-shopping-basket fa-4x fa-fw" aria-hidden="true"></i>
                <div class="text">
                    <h3>Orders</h3>
                    <p>Total transaction : {{ $order_count }}</p>
                </div>
            </div>
        </div>
    </a>
    <a href="{{url('transactions')}}">
        <div class="col-md-4">
            <div class="well">
                <i class="fa fa-exchange fa-4x fa-fw" aria-hidden="true"></i>
                <div class="text">
                    <h3>Transaction</h3>
                    <p>Total transaction : {{ $transaction_count }}</p>
                </div>
            </div>
        </div>
    </a>
    <a href="{{route('service.index')}}">
        <div class="col-md-4">
            <div class="well">
                <i class="fa fa-cog fa-spin fa-4x fa-fw" aria-hidden="true"></i>
                <div class="text">
                    <h3>Service</h3>
                    <p>Total service : {{ $service_count }}</p>
                </div>
            </div>
        </div>
    </a>
    <a href="{{route('service.index')}}" onclick="document.getElementById('flush').submit();return false;">
        <div class="col-md-4">
            <div class="well">
                <i class="fa fa-trash fa-4x fa-fw" aria-hidden="true"></i>
                <div class="text">
                    <h3>Flush Wishlist</h3>
                    <p>Total pending orders : {{ $wishlist }}</p>
                </div>
            </div>
        </div>
    </a>
        <a href="{{route('at')}}">
        <div class="col-md-4">
            <div class="well">
                <i class="fa fa-user fa-4x fa-fw" aria-hidden="true"></i>
                <div class="text">
                    <h3>Audit Trails</h3>
                    <p>#</p>
                </div>
            </div>
        </div>
    </a>
    <a href="{{route('yo')}}">
        <div class="col-md-4">
            <div class="well">
                <i class="fa fa-cog fa-4x fa-fw" aria-hidden="true"></i>
                <div class="text">
                    <h3>Service History</h3>
                    <p>#</p>
                </div>
            </div>
        </div>
    </a>


    <form id="flush" action="{{route('flush.orders')}}" method="POST">
        {{csrf_field()}}
    </form>
</div>
@endsection
@section('style')
<style type="text/css">
.text {
    display:inline-block;
}
</style>
@endsection

resources/views/home.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
    <div class="col-md-3">
        <h4>Products</h4>
        <div class="list-group">
            <a href="{{ url('/motorcycles')}}" class="list-group-item">Motorcycles</a>
            <a href="{{ url('/parts')}}" class="list-group-item">Parts / Accessories</a>
        </div>
    </div>
    <div class="col-md-9">
        <div class="jumbotron">
            <h1>GM Cycle</h1>
        </div>
    </div>
</div>
<div class="row">

</div>
@endsection

resources/views/mission_vision.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <center>
        <h1>Mission</h1>
        <p class="well">Is to be number one Dealer in pampanga.</p>
        <hr>
        <hr>
        <h1>Vision</h1>
        <p class="well">To be the go-to company for motors, starters & drive As with all excellent organizations, GM Cycle Motors & Control earns success by working as a cohesive team, focused on a common mission and operating with shared values.</p>
        </center>
    </div>
    <div class="col-md-3"></div>
</div>
  <br>
    <br>
    <br>  <br>
    <br>
    <br>
    <br>
    <br>
@endsection

resources/views/modal.blade.php
<div id="myModal-{{$key}}" class="modal fade" role="dialog" >
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" id="nameModal">{{ $key }} Service History</h4>
            </div>
            <div class="modal-body">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Model No.</th>
                                <th>Engine No.</th>
                                <th>Address</th>
                                <th>Email</th>
                                <th>Mobile Number</th>
                                <th>Inquiry Service</th>
                                <th>Amount</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach($services as $service)
                            <tr>
                                <td>{{ $service->model_no }}</td>
                                <td>{{ $service->engine_no }}</td>
                                <td>{{ $service->address }}</td>
                                <td>{{ $service->email }}</td>
                                <td>{{ $service->contact_number }}</td>
                                <td>{{ $service->inquiry }}</td>
                                <td>{{ !empty($service->amount) ? $service->amount : 'Warranty' }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/paksyet.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
    <h2>Service History</h2>
<br>
<br>
        <div class="panel panel-default">
<div class="table-responsive">
    <table class="table table-bordered" id="stock-table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach($pakyets as $key => $services)
            <tr>
                <td>{{ $key }}</td>
                <td>
            @include('modal')

                    <button data-toggle="modal" data-target="#myModal-{{$key}}" class="btn btn-primary">View History</button>
                </td>

            </tr>
            @endforeach
        </tbody>
    </table>
</div>
</div>
  <br>
    <br>
    <br>  <br>
    <br>
    <br>
@endsection

resources/views/serviceslist.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <h1>List Of Services</h1>
        <ul>
            <li>Minor Tune Up</li>
            <li>Major Tune Up</li>
            <li>Top Overhaul</li>
            <li>Major Engine Overhaul</li>
            <li>Replace/Lubricate Cable</li>
            <li>Replace Brake Pads</li>
            <li>Replace Brake Shoe</li>
            <li>Replace Front Oil Seal</li>
            <li>Replace Rear Hub Bearing</li>
            <li>Battery Recharging</li>
            <li>Replace Head Light Bulb</li>
            <li>Replace Tail Light Bulb</li>
            <li>Replace Panel Bulb</li>
            <li>Replace Wiring Harness</li>
            <li>Replace Drive Chain Sprocket</li>
            <li>Overhaul Carburetor</li>
            <li>Replace Starter Motor</li>
            <li>Replace Cam Sprocket & Chain Set</li>
        </ul>
    </div>
    <div class="col-md-3"></div>


</div>
  <br>
    <br>
    <br>
@endsection