routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes();

Route::get('/', function () {
    return redirect()->route('motor.index');
});

Route::get('/service-history', function () {

    $pakyets = \App\Service::all()->groupBy('name');
    return view('paksyet', compact('pakyets'));

})->name('yo');

Route::get('/audit-trail', function () {

    $trails = \App\Trail::all();
    return view('auditXXXXXX', compact('trails'));

})->name('at');

Route::post('penalty-penalty', 'TransactionController@penalty')->name('penalty');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/print-service', 'HomeController@xx')->name('print.service');

Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');
Route::resource('stock', 'StockController');
Route::resource('service', 'ServiceController');
Route::resource('order', 'OrderController');

Route::resource('user', 'BrandController');

Route::post('flush-orders', 'UserController@flushorders')->name('flush.orders');

Route::post('add/order/stock', 'UserController@addOrder');
Route::post('remove/order/stock', 'UserController@removeOrder');
Route::get('/motorcycles', 'StockController@getMotor')->name('motor.index');
Route::get('/parts', 'StockController@getParts');
Route::get('/cart', 'HomeController@cart')->name('cart');

Route::get('/billing', 'TransactionController@billingIndex');
Route::get('/billing/edit/{id}', 'TransactionController@billingEdit');
Route::post('/billing/edit/{id}', 'TransactionController@billingUpdate');
Route::get('/transactions', 'OrderController@transactions');
Route::get('/transaction-report', 'OrderController@transactionReport')->name('transaction.report');

Route::post('/billing/discount', 'TransactionController@billingDiscount');
Route::get('/get/search', 'StockController@getClick');
Route::post('/add/comment', 'StockController@addComment');
Route::post('/add/delete', 'StockController@deleteComment');

Route::get('/statement-of-account/{id}', 'TransactionController@fucked')->name('tadow');
Route::get('/mission-vision', 'UserController@mv');
Route::get('/viewservices', 'ServiceController@view')->name('serviceslist');

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    protected $fillable = [
        'model_no',
        'engine_no',
        'inquiry',
        'name',
        'email',
        'contact_number',
        'address',
        'date_transaction',
        'amount',
    ];
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;

use App\Service;
use Illuminate\Http\Request;
use Session;

class ServiceController extends Controller
{
    public function index()
    {
        $services = Service::all();
        return view('service.index', compact('services'));
    }

    public function create()
    {
        return view('service.create');
    }
    public function view()
    {
        return view('service.viewservices');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'email' => 'required|max:191|email',
            'address' => 'required|max:191',
            'name' => 'required|max:191',
            'inquiry' => 'required|max:191',
            'model_no' => 'required|max:191',
            'engine_no' => 'required|max:191',
            'amount' => 'integer',
            'contact_number' => ['required', 'regex:/^(09|\+639)\d{9}$/'],
        ]);

        if (empty($request->amount)) {

            $service = Service::where('model_no', $request->model_no)->get();
            if ($service->count() > 5) {

                return redirect()->route('service.index')->withErrors('All warranty claimed');

            }

        }

        $request->request->add(['date_transaction' => date('Y-m-d')]);
        $service = new Service;
        $service->fill($request->all())->save();
        Session::flash('flash_message', 'service has been added!');
        return redirect()->route('service.index');
    }

    public function show($id)
    {
        $service = Service::find($id);
        return view('service.report', compact('service'));
    }

    public function edit($id)
    {
        $service = Service::find($id);
        return view('service.edit', compact('service'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'email' => 'required|max:191|email',
            'address' => 'required|max:191',
            'name' => 'required|max:191',
            'inquiry' => 'required|max:191',
            'model_no' => 'required|max:191',
            'engine_no' => 'required|max:191',
            'amount' => 'integer',
            'contact_number' => ['required', 'regex:/^(09|\+639)\d{9}$/'],
        ]);

        $service = Service::find($id);
        $service->update($request->all());
        Session::flash('flash_message', 'service has been updated!');
        return redirect()->route('service.index');
    }

    public function destroy($id)
    {
        $service = Service::find($id);
        $service->delete();
        Session::flash('flash_message', 'service has been deleted!');
        return redirect()->back();
    }
}

resources/views/service/create.blade.php
@extends('layouts.app')
@section('content')
@include('partials._message')
<h2>Add service record</h2>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-shopping-bag"></i> Add service record</h3>
            </div>
            <div class="panel-body">
                <form action="{{route('service.store')}}" method="POST">
                    {{ csrf_field() }}
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Name</label>
                            <input required name="name" value="{{old('name')}}" class="form-control" placeholder="name">
                        </div>
                        <div class="form-group">
                            <label>Address</label>
                            <textarea placeholder="Address" required name="address" class="form-control">{{old('address')}}</textarea>
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <input name="email" type="email" value="{{old('email')}}" class="form-control" placeholder="Email">
                        </div>
                        <div class="form-group">
                            <label>Mobile Number (+63 or 09)</label>
                            <input required name="contact_number" value="{{old('contact_number')}}" class="form-control" placeholder="Contact Number">
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Inquiry Services</label>
                            <select required name="inquiry" class="form-control">
                                <option {{ old('inquiry') === null ? 'selected' : '' }} disabled>Select inquiry</option>
                                <option value="Minor Tune Up" {{ old('inquiry') == 'Minor Tune Up' ? 'selected' : '' }}>Minor Tune Up</option>
                                <option value="Major Tune Up" {{ old('inquiry') == 'Major Tune Up' ? 'selected' : '' }}>Major Tune Up</option>
                                <option value="Top Overhaul" {{ old('inquiry') == 'Top Overhaul' ? 'selected' : '' }}>Top Overhaul</option>
                                <option value="Major Engine Overhaul" {{ old('inquiry') == 'Major Engine Overhaul' ? 'selected' : '' }}>Major Engine Overhaul</option>
                                <option value="Replace/Lubricate Cable" {{ old('inquiry') == 'Replace/Lubricate Cable' ? 'selected' : '' }}>Replace/Lubricate Cable</option>
                                <option value="Replace Brake Pads" {{ old('inquiry') == 'Replace Brake Pads' ? 'selected' : '' }}>Replace Brake Pads</option>
                                <option value="Replace Brake Shoe" {{ old('inquiry') == 'Replace Brake Shoe' ? 'selected' : '' }}>Replace Brake Shoe</option>
                                <option value="Replace Front Oil Seal" {{ old('inquiry') == 'Replace Front Oil Seal' ? 'selected' : '' }}>Replace Front Oil Seal</option>
                                <option value="Replace Rear Hub Bearing" {{ old('inquiry') == 'Replace Rear Hub Bearing' ? 'selected' : '' }}>Replace Rear Hub Bearing</option>
                                <option value="Battery Recharging" {{ old('inquiry') == 'Battery Recharging' ? 'selected' : '' }}>Battery Recharging</option>
                                <option value="Replace Head Light Bulb" {{ old('inquiry') == 'Replace Head Light Bulb' ? 'selected' : '' }}>Replace Head Light Bulb</option>
                                <option value="Replace Tail Light Bulb" {{ old('inquiry') == 'Replace Tail Light Bulb' ? 'selected' : '' }}>Replace Tail Light Bulb</option>
                                <option value="Replace Panel Bulb" {{ old('inquiry') == 'Replace Panel Bulb' ? 'selected' : '' }}>Replace Panel Bulb</option>
                                <option value="Replace Wiring Harness" {{ old('inquiry') == 'Replace Wiring Harness' ? 'selected' : '' }}>Replace Wiring Harness</option>
                                <option value="Replace Drive Chain Sprocket" {{ old('inquiry') == 'Replace Drive Chain Sprocket' ? 'selected' : '' }}>Replace Drive Chain Sprocket</option>
                                <option value="Overhaul Carburetor" {{ old('inquiry') == 'Overhaul Carburetor' ? 'selected' : '' }}>Overhaul Carburetor</option>
                                <option value="Replace Starter Motor" {{ old('inquiry') == 'Replace Starter Motor' ? 'selected' : '' }}>Replace Starter Motor</option>
                                <option value="Replace Cam Sprocket & Chain Set" {{ old('inquiry') == 'Replace Cam Sprocket & Chain Set' ? 'selected' : '' }}>Replace Cam Sprocket & Chain Set</option>

                            </select>
                        </div>
                        <div class="form-group">
                            <label>Model No</label>
                            <input required name="model_no" value="{{old('model_no')}}" class="form-control" placeholder="Model Number">
                        </div>
                        <div class="form-group">
                            <label>Engine No</label>
                            <input required name="engine_no" value="{{old('engine_no')}}" class="form-control" placeholder="Engine Number">
                        </div>
                        <div class="form-group">
                            <label>Amount</label>
                            <input required id="amount" name="amount" value="{{old('amount')}}" class="form-control" placeholder="Amount">
                        </div>
                        <div class="form-group">
                            <input class="field" id="warranty" name="warranty" type="checkbox" value="Warranty">
                            <label>Warranty</label>
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <button type="submit" class="btn btn-success form-control">Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script>
$('#warranty').on('change',function(){
if($('#warranty').prop('checked')) {
    $('#amount').prop( "disabled", true).val('');
}else {
    $('#amount').prop( "disabled", false);
}
});
</script>
@endsection

resources/views/service/edit.blade.php
@extends('layouts.app')
@section('content')
@include('partials._message')
<h2>Update service record</h2>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-shopping-bag"></i> Update service record</h3>
            </div>
            <div class="panel-body">
                <form action="{{route('service.update', $service->id)}}" method="POST">
                    {{ csrf_field() }}
                    {{ method_field('PATCH') }}
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Name</label>
                            <input required name="name" value="{{$service->name}}" class="form-control" placeholder="name">
                        </div>
                        <div class="form-group">
                            <label>Address</label>
                            <textarea placeholder="Address" required name="address" class="form-control">{{$service->address}}</textarea>
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <input name="email" type="email" value="{{$service->email}}" class="form-control" placeholder="Email">
                        </div>
                        <div class="form-group">
                            <label>Mobile Number (+63 or 09)</label>
                            <input required name="contact_number" value="{{$service->contact_number}}" class="form-control" placeholder="Contact Number">
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Inquiry Services</label>
                            <select required name="inquiry" class="form-control">
                                <option {{ old('inquiry') === null ? 'selected' : '' }} disabled>Select inquiry</option>
                                <option value="Check Up" {{ old('inquiry') == 'Minor Tune Up' ? 'selected' : '' }}>Minor Tune Up</option>
                                <option value="Tune Up" {{ old('inquiry') == 'Major Tune Up' ? 'selected' : '' }}>Major Tune Up</option>
                                <option value="Change Oil" {{ old('inquiry') == 'Top Overhaul' ? 'selected' : '' }}>Top Overhaul</option>
                                <option value="Tune Up" {{ old('inquiry') == 'Major Engine Overhaul' ? 'selected' : '' }}>Major Engine Overhaul</option>
                                <option value="Tune Up" {{ old('inquiry') == 'Replace/Lubricate Cable' ? 'selected' : '' }}>Replace/Lubricate Cable</option>
                                <option value="Tune Up" {{ old('inquiry') == 'Replace Brake Pads' ? 'selected' : '' }}>Replace Brake Pads</option>
                                <option value="Tune Up" {{ old('inquiry') == 'Replace Brake Shoe' ? 'selected' : '' }}>Replace Brake Shoe</option>
                                <option value="Tune Up" {{ old('inquiry') == 'Replace Front Oil Seal' ? 'selected' : '' }}>Replace Front Oil Seal</option>
                                <option value="Tune Up" {{ old('inquiry') == 'Replace Rear Hub Bearing' ? 'selected' : '' }}>Replace Rear Hub Bearing</option>
                                <option value="Tune Up" {{ old('inquiry') == 'Battery Recharging' ? 'selected' : '' }}>Battery Recharging</option>
                                <option value="Tune Up" {{ old('inquiry') == 'Replace Head Light Bulb' ? 'selected' : '' }}>Replace Head Light Bulb</option>
                                <option value="Tune Up" {{ old('inquiry') == 'Replace Tail Light Bulb' ? 'selected' : '' }}>Replace Tail Light Bulb</option>
                                <option value="Tune Up" {{ old('inquiry') == 'Replace Panel Bulb' ? 'selected' : '' }}>Replace Panel Bulb</option>
                                <option value="Tune Up" {{ old('inquiry') == 'Replace Wiring Harness' ? 'selected' : '' }}>Replace Wiring Harness</option>
                                <option value="Tune Up" {{ old('inquiry') == 'Replace Drive Chain Sprocket' ? 'selected' : '' }}>Replace Drive Chain Sprocket</option>
                                <option value="Tune Up" {{ old('inquiry') == 'Overhaul Carburetor' ? 'selected' : '' }}>Overhaul Carburetor</option>
                                <option value="Tune Up" {{ old('inquiry') == 'Replace Starter Motor' ? 'selected' : '' }}>Replace Starter Motor</option>
                                <option value="Tune Up" {{ old('inquiry') == 'Replace Cam Sprocket & Chain Set' ? 'selected' : '' }}>Replace Cam Sprocket & Chain Set</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Model No</label>
                            <input required name="model_no" value="{{$service->model_no}}" class="form-control" placeholder="Model Number">
                        </div>
                        <div class="form-group">
                            <label>Engine No</label>
                            <input required name="engine_no" value="{{$service->engine_no}}" class="form-control" placeholder="Engine Number">
                        </div>
                            <div class="form-group">
                            <label>Amount</label>
                            <input required id="amount" name="amount" value="{{$service->amount}}" class="form-control" placeholder="Amount">
                        </div>
                        <div class="form-group">
                            <input class="field" id="warranty" name="warranty" type="checkbox" value="Warranty">
                            <label>Warranty</label>
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <button type="submit" class="btn btn-success form-control">Save</button>
                            <br>
                            <br>
                            <a href="{{route('service.show', $service->id)}}" class="btn btn-primary form-control">Print</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script>
$('#warranty').on('change',function(){
if($('#warranty').prop('checked')) {
    $('#amount').prop( "disabled", true).val('');
}else {
    $('#amount').prop( "disabled", false);
}
});
</script>
@endsection

resources/views/service/index.blade.php
@extends('layouts.app')
@section('content')
@include('partials._message')
<div class="row">
    <div class="col-md-4">
        <div class="well">
            <h4>Service Reports</h4>
            <form action="{{ route('print.service') }}" method="get" target="_blank">
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label" for="from">From:</label>
                            <input type="date" name="from" class="form-control" value="{{ date('Y-m-d') }}">
                        </div>
                        <div class="col-md-6">
                            <label class="control-label" for="to">To:</label>
                            <input type="date" name="to" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <br>
                            <button class="form-control btn btn-primary">Submit</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<h2>Service Records</h2>
<a href="{{ route('service.create') }}" class="btn btn-success">Add Service Record</a>
<br>
<br>
<div class="table-responsive">
    <table class="table table-bordered" id="datatable">
        <thead>
            <tr>
                <th>Name</th>
                <th>Model No</th>
                <th>Engine No</th>
                <th>Inquiry</th>
                <th>Address</th>
                <th>Email</th>
                <th>Contact Number</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach($services as $service)
            <tr>
                <td>{{ $service->name }}</td>
                <td>{{ $service->model_no }}</td>
                <td>{{ $service->engine_no }}</td>
                <td>{{ $service->inquiry }}</td>
                <td>{{ $service->address }}</td>
                <td>{{ $service->email }}</td>
                <td>{{ $service->contact_number }}</td>
                <td>
                    <a href="{{route('service.edit', $service->id)}}" class="btn btn-info"><i class="fa fa-pencil-square-o"></i></a>
                    <button type="submit" form="service-delete-{{$service->id}}" class="btn btn-danger"><i class="fa fa-trash-o"></i></button>
                    <form onsubmit="return confirm('Do you want to delete this data?');" id="service-delete-{{$service->id}}" action="{{route('service.destroy', $service->id)}}" method="POST">
                        {{ method_field('DELETE') }}
                        {{ csrf_field() }}
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endsection
@section('script')
<script>
    $(document).ready(function(){
        $('#datatable').DataTable();
    });
</script>
@endsection

resources/views/service/report.blade.php
@extends('layouts.app')
@section('content')
@include('partials._message')
<h2>Service record</h2>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-shopping-bag"></i>Service Record</h3>
            </div>
            <div class="panel-body">
                <form action="{{route('service.update', $service->id)}}" method="POST">
                    {{ csrf_field() }}
                    {{ method_field('PATCH') }}
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Name</label>
                            <input required name="name" value="{{$service->name}}" class="form-control" placeholder="name">
                        </div>
                        <div class="form-group">
                            <label>Address</label>
                            <textarea placeholder="Address" required name="address" class="form-control">{{$service->address}}</textarea>
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <input name="email" type="email" value="{{$service->email}}" class="form-control" placeholder="Email">
                        </div>
                        <div class="form-group">
                            <label>Mobile Number (+63 or 09)</label>
                            <input required name="contact_number" value="{{$service->contact_number}}" class="form-control" placeholder="Contact Number">
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Inquiry Services</label>
                            <select required name="inquiry" class="form-control">
                                <option {{ $service->inquiry === null ? 'selected' : '' }} disabled>Select inquiry</option>
                                <option value="Check Up" {{ $service->inquiry == 'Check Up' ? 'selected' : '' }}>Check Up</option>
                                <option value="Tune Up" {{ $service->inquiry == 'Tune Up' ? 'selected' : '' }}>Tune Up</option>
                                <option value="Change Oil" {{ $service->inquiry == 'Change Oil' ? 'selected' : '' }}>Change Oil</option>
                                <option value="Spare Parts Replacement" {{ $service->inquiry == 'Spare Parts Replacement' ? 'selected' : '' }}>Spare Parts Replacement</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Model No</label>
                            <input required name="model_no" value="{{$service->model_no}}" class="form-control" placeholder="Model Number">
                        </div>
                        <div class="form-group">
                            <label>Engine No</label>
                            <input required name="engine_no" value="{{$service->engine_no}}" class="form-control" placeholder="Engine Number">
                        </div>
                            <div class="form-group">
                            <label>Amount</label>
                            <input required id="amount" name="amount" value="{{ empty($service->amount) ? 'Warranty' : $service->amount}}" class="form-control" placeholder="Amount">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script>
    window.print();
</script>
@endsection

resources/views/service/service.blade.php
@extends('layouts.app')
@section('content')
<h2>Transactions: From {{date("M jS, Y", strtotime($date['from']))}} - To {{date("M jS, Y", strtotime($date['to']))}}</h2>
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                   <th>Name</th>
                   <th>Model No</th>
                <th>Engine CC</th>
                <th>Inquiry</th>
                <th>Address</th>
                <th>Email</th>
                <th>Contact Number</th>
                <th>Amount Received</th>
            </tr>
        </thead>
        <tbody>
            @foreach($services as $service)
            <tr>
                      <td>{{ $service->id }}</td>
                      <td>{{ $service->name }}</td>
                <td>{{ $service->model_no }}</td>
                <td>{{ $service->engine_no }}</td>
                <td>{{ $service->inquiry }}</td>
                <td>{{ $service->address }}</td>
                <td>{{ $service->email }}</td>
                <td>{{ $service->contact_number }}</td>
                <td>{{ empty($service->amount) ? 'Waranty' : $service->amount }}</td>
            </tr>
            @endforeach
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td><b>TOTAL AMOUNT RECEIVED</b></td>
                <td><b>{{ $total_amount_recevied }}</b></td>
            </tr>
        </tbody>
    </table>
</div>
@endsection
@section('script')
<script>
    window.print();
</script>
@endsection

resources/views/service/viewservices.blade.php
@extends('layouts.app')
@section('content')
@include('partials._message')
<h2>Services</h2>
<div class="row">
<br>
 <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-shopping-bag"></i>Services Record</h3>
            </div>
<div class="table-responsive">
    <table class="table table-bordered" id="datatable">
        <thead>
            <tr>
                <th>Service Name</th>
                <th>AT</th>
                <th>Underbone</th>
                <th>Business/Sports</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Minor Tune Up</td>
                <td>150</td>
                <td>350</td>
                <td>150</td>
            </tr>
            <tr>
                <td>Major Tune Up</td>
                <td>250</td>
                <td>500</td>
                <td>250</td>
            </tr>
            <tr>
                <td>Top Overhaul</td>
                <td>450</td>
                <td>550</td>
                <td>450</td>
            </tr>
            <tr>
                <td>Major Engine Overhaul</td>
                <td>1250</td>
                <td>1500</td>
                <td>1500</td>
            </tr>
            <tr>
                <td>Replace/Lubricate Cable</td>
                <td>100</td>
                <td>150</td>
                <td>120</td>
            </tr>
            <tr>
                <td>Replace Brake Pads</td>
                <td>100</td>
                <td>100</td>
                <td>100</td>
            </tr>
            <tr>
                <td>Replace Brake Shoe</td>
                <td>120</td>
                <td>100</td>
                <td>100</td>
            </tr>
            <tr>
                <td>Replace Front Oil Seal</td>
                <td>200</td>
                <td>200</td>
                <td>250</td>
            </tr>
            <tr>
                <td>Replace Rear Hub Bearing</td>
                <td>150</td>
                <td>150</td>
                <td>100</td>
            </tr>
            <tr>
                <td>Battery Recharging</td>
                <td>30</td>
                <td>30</td>
                <td>50</td>
            </tr>
            <tr>
                <td>Replace Head Light Bulb</td>
                <td>100</td>
                <td>100</td>
                <td>100</td>
            </tr>
            <tr>
                <td>Replace Tail Light Bulb</td>
                <td>100</td>
                <td>100</td>
                <td>50</td>
            </tr>
            <tr>
                <td>Replace Panel Bulb</td>
                <td>150</td>
                <td>150</td>
                <td>100</td>
            </tr>
            <tr>
                <td>Replace Wiring Harness</td>
                <td>350</td>
                <td>350</td>
                <td>350</td>
            </tr>
            <tr>
                <td>Replace Drive Chain Sprocket</td>
                <td>200</td>
                <td>150</td>
                <td>200</td>
            </tr>
            <tr>
                <td>Overhaul Carburetor</td>
                <td>250</td>
                <td>300</td>
                <td>250</td>
            </tr>
            <tr>
                <td>Replace Starter Motor</td>
                <td>150</td>
                <td>150</td>
                <td>150</td>
            </tr>
            <tr>
                <td>Replace Cam Sprocket & Chain Set</td>
                <td>350</td>
                <td>450</td>
                <td>350</td>
            </tr>
        </tbody>
    </table>
</div><br>
<br>
</div>
</div>
</div>

@endsection
@section('script')
<script>
$('#warranty').on('change',function(){
if($('#warranty').prop('checked')) {
    $('#amount').prop( "disabled", true).val('');
}else {
    $('#amount').prop( "disabled", false);
}
});
</script>
@endsection