routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes();

Route::get('/', function () {
    return redirect()->route('motor.index');
});

Route::get('/service-history', function () {

    $pakyets = \App\Service::all()->groupBy('name');
    return view('paksyet', compact('pakyets'));

})->name('yo');

Route::get('/audit-trail', function () {

    $trails = \App\Trail::all();
    return view('auditXXXXXX', compact('trails'));

})->name('at');

Route::post('penalty-penalty', 'TransactionController@penalty')->name('penalty');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/print-service', 'HomeController@xx')->name('print.service');

Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');
Route::resource('stock', 'StockController');
Route::resource('service', 'ServiceController');
Route::resource('order', 'OrderController');

Route::resource('user', 'BrandController');

Route::post('flush-orders', 'UserController@flushorders')->name('flush.orders');

Route::post('add/order/stock', 'UserController@addOrder');
Route::post('remove/order/stock', 'UserController@removeOrder');
Route::get('/motorcycles', 'StockController@getMotor')->name('motor.index');
Route::get('/parts', 'StockController@getParts');
Route::get('/cart', 'HomeController@cart')->name('cart');

Route::get('/billing', 'TransactionController@billingIndex');
Route::get('/billing/edit/{id}', 'TransactionController@billingEdit');
Route::post('/billing/edit/{id}', 'TransactionController@billingUpdate');
Route::get('/transactions', 'OrderController@transactions');
Route::get('/transaction-report', 'OrderController@transactionReport')->name('transaction.report');

Route::post('/billing/discount', 'TransactionController@billingDiscount');
Route::get('/get/search', 'StockController@getClick');
Route::post('/add/comment', 'StockController@addComment');
Route::post('/add/delete', 'StockController@deleteComment');

Route::get('/statement-of-account/{id}', 'TransactionController@fucked')->name('tadow');
Route::get('/mission-vision', 'UserController@mv');
Route::get('/viewservices', 'ServiceController@view')->name('serviceslist');

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    protected $fillable = [
        'first_name',
        'last_name',
        'middle_name',
        'contact',
        'address',
        'email',
        'password',
        'mobile_number',
        'birthday',
        'gender',
        'status',
        'monthly_income',
        'other_income_source',
        'other_income_amount',
        'spouse_name',
        'spouse_contact',
        'employer',
        'company_address',
        'position',
        'employement_status',
        'user_type',
        'is_active',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    public function transactions()
    {
        return $this->hasMany('App\Transaction', 'user_id');
    }

    public function orders()
    {
        return $this->hasMany('App\Order', 'user_id');
    }

    public function comments()
    {
        return $this->hasMany('App\Comment', 'user_id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Order;
use App\Stock;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Session;

class UserController extends Controller
{

    public function flushorders()
    {
        $orders = Order::where('status', 'wishlist')->get();
        $counter = 0;
        foreach ($orders as $order) {
            if (Carbon::parse($order->created_at)->addHours(48)->lte(Carbon::now())) {
                $order->delete();
                $counter++;
            }
        }
        if ($counter) {
            Session::flash('flash_message', $counter . ' Orders has been flushed!');
        }
        return redirect()->back();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function mv()
    {
        return view('mission_vision');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function welcome()
    {
        $dMotors = Stock::where('quantity', '!=', '0')->where('type', 'motor')->get();
        $motors = [];
        $check = ['completed', 'on-going'];
        foreach ($dMotors as $v) {
            if ($v->order()->first()) {
                $order = $v->order()->first();
                if (in_array($order->status, $check)) {
                    continue;
                }
            }
            $motors[] = $v;
        }
        $dParts = Stock::where('quantity', '!=', '0')->where('type', 'part')->get();
        $parts = [];
        foreach ($dParts as $v) {
            if ($v->order()->first()) {
                $order = $v->order()->first();
                if (in_array($order->status, $check)) {
                    continue;
                }
            }
            $parts[] = $v;
        }
        return view('welcome', compact('motors', 'parts'));
    }

    public function addOrder(Request $request)
    {
        if (empty($request->id)) {
            return response()->json(['error' => 'Bad Request'], 403);
        }
        $user = \Auth::user();
        $temp_discount = 0;
        if (empty($request->quantity)) {
            $temp_discount = 0;
        } else {
            $temp_discount = $request->quantity;
        }

        $data = [
            'user_id' => \Auth::id(),
            'stock_id' => $request->id,
            'quantity' => $temp_discount,
            'status' => 'wishlist',
        ];
        $exist = Order::where('user_id', $data['user_id'])->where('stock_id', $data['stock_id'])->count();
        if ($exist) {
            return response()->json(['error' => 'Bad Request'], 403);
        }
        $order = new Order;
        $order->fill($data)->save();
        return redirect()->back();
    }

    public function removeOrder(Request $request)
    {
        if (empty($request->id)) {
            return response()->json(['error' => 'Bad Request'], 403);
        }
        $user = \Auth::user();
        $data = [
            'user_id' => \Auth::id(),
            'stock_id' => $request->id,
        ];
        $exist = Order::where('user_id', $data['user_id'])->where('stock_id', $data['stock_id'])->first();
        $del = Order::find($exist->id);
        $del->delete();
        return response()->json();

    }
}

resources/views/user/edit.blade.php
@extends('layouts.app')
@section('content')
@include('partials._message')
<div class="row">
    <div class="col-md-12">
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">Account Settings</div>
            <div class="panel-body">
                <form action="{{route('user.update', $user->id)}}" method="POST">
                    {{ method_field('PATCH') }}
                    {{ csrf_field() }}
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>First Name</label>
                                <input required name="first_name" value="{{$user->first_name}}" class="form-control" placeholder="First Name">
                            </div>
                            <div class="form-group">
                                <label>Middle Name</label>
                                <input name="middle_name" value="{{$user->middle_name}}" class="form-control" placeholder="Middle Name">
                            </div>
                            <div class="form-group">
                                <label>Last Name</label>
                                <input name="last_name" value="{{$user->last_name}}" class="form-control" placeholder="Last Name">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>Address</label>
                                <textarea name="address" class="form-control">{{$user->address}}</textarea>
                            </div>
                            <div class="form-group">
                                <label>Mobile Number (+63 or 09)</label>
                                <input name="mobile_number" value="{{$user->mobile_number}}" class="form-control" placeholder="Mobile Number">
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                <button type="submit" class="btn btn-success form-control">Update</button>
                            </div>
                        </div>
                    </div>
                </form>
                <h2>Transactions</h2>
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Product</th>
                                <th>Amount Paid</th>
                                <th>Date Transacted</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($trans as $x)
                            <tr>
                                <td>{{ $x->id }}</td>
                                <td>{{ $x->stock()->first()->name }}</td>
                                <td>{{ $x->amount_received }}</td>
                                <td>{{ $x->date_transaction }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection