routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes();

Route::get('/', function () {
    return redirect()->route('motor.index');
});

Route::get('/service-history', function () {

    $pakyets = \App\Service::all()->groupBy('name');
    return view('paksyet', compact('pakyets'));

})->name('yo');

Route::get('/audit-trail', function () {

    $trails = \App\Trail::all();
    return view('auditXXXXXX', compact('trails'));

})->name('at');

Route::post('penalty-penalty', 'TransactionController@penalty')->name('penalty');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/print-service', 'HomeController@xx')->name('print.service');

Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');
Route::resource('stock', 'StockController');
Route::resource('service', 'ServiceController');
Route::resource('order', 'OrderController');

Route::resource('user', 'BrandController');

Route::post('flush-orders', 'UserController@flushorders')->name('flush.orders');

Route::post('add/order/stock', 'UserController@addOrder');
Route::post('remove/order/stock', 'UserController@removeOrder');
Route::get('/motorcycles', 'StockController@getMotor')->name('motor.index');
Route::get('/parts', 'StockController@getParts');
Route::get('/cart', 'HomeController@cart')->name('cart');

Route::get('/billing', 'TransactionController@billingIndex');
Route::get('/billing/edit/{id}', 'TransactionController@billingEdit');
Route::post('/billing/edit/{id}', 'TransactionController@billingUpdate');
Route::get('/transactions', 'OrderController@transactions');
Route::get('/transaction-report', 'OrderController@transactionReport')->name('transaction.report');

Route::post('/billing/discount', 'TransactionController@billingDiscount');
Route::get('/get/search', 'StockController@getClick');
Route::post('/add/comment', 'StockController@addComment');
Route::post('/add/delete', 'StockController@deleteComment');

Route::get('/statement-of-account/{id}', 'TransactionController@fucked')->name('tadow');
Route::get('/mission-vision', 'UserController@mv');
Route::get('/viewservices', 'ServiceController@view')->name('serviceslist');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>{{ config('app.name', 'GM Cycle') }}</title>
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
        <link href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        @yield('style')
    </head>
    <body>
        <div id="app">
            <nav class="navbar navbar-default navbar-static-top">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{{ url('/') }}">
                            {{ config('app.name', 'GM Cycle') }}
                        </a>
                    </div>
                    <div class="collapse navbar-collapse" id="app-navbar-collapse">
                        <ul class="nav navbar-nav">
                            &nbsp;
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                            <li><a href="{{ url('/viewservices') }}">Services</a></li>
                            <li><a href="{{ url('mission-vision') }}">About Us</a></li>



                            @else
                            @if(Auth::user())
                            @if(auth()->user()->user_type != 'Admin')
                            <li><a href="{{ route('cart') }}">Cart</a></li>
                            <li><a href="{{ route('serviceslist') }}">Services</a></li>
                            @endif
                            @endif
                            @if(Auth::user()->user_type == 'Admin')
                            <li><a href="{{ route('service.index') }}">Services</a></li>
                            <li><a href="{{ route('dashboard') }}">Dashboard</a></li>
                            @endif
                            <li><a href="{{ url('mission-vision') }}">About Us</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->first_name }} {{ Auth::user()->last_name }} <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                            <li><a href="{{route('user.index')}}">Account Settings</a></li>
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                            document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>
                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                            @endguest
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="container-fluid">
                @yield('content')
            </div>
        </div>
<footer style="background-color:white; padding: 15px;" class="footer text-center"> 2018 &copy;  GMCYCLE - Please contact us 0975312320</footer>
        <script src="{{ asset('js/app.js') }}"></script>
        <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
        <script src="https://unpkg.com/sweetalert2@7.1.2/dist/sweetalert2.all.js"></script>
        @yield('script')
    </body>
</html>